### ISSUE TITLE
Error Logs

### ISSUE THREAD

**Issue by UnluckyPandaa** [ShermansWorld/Governor#1]
https://bin.bloom.host/galefuferi
https://bin.bloom.host/uhoxiboqik.md
https://bin.bloom.host/ecutafiqiz

**Comment by ShermansWorld** [comment]
Did you get  the newest version, Governor 1.1.1?

https://www.spigotmc.org/resources/governor.101482/history

**Comment by ShermansWorld** [comment]
Version 1.1.1 Changelog:
- **Fixed bug where IncomeTaxListener gets disabled**  <--- (I think this version fixes the error you are having)
- Added additional exception handling for InactiveTownListener
- A few incorrect/ambiguous chat messages revised
