### ISSUE TITLE
1.1.1 Issue

### ISSUE THREAD

**Issue by UnluckyPandaa** [ShermansWorld/Governor#2]
https://bin.bloom.host/tekikamure.properties

lmk if you need more info!

**Comment by ShermansWorld** [comment]
What economy-related plugins are you using on your server? This is an error I haven't seen yet but I will work on it for the next patch. I would recommend disabling the income tax feature until this patch comes out.

**Comment by UnluckyPandaa** [comment]
Essentials/Vault/Towny are the most notable ones I can really think of.

But will stop using the plugin for now until its patched!

**Comment by ShermansWorld** [comment]
Governor 1.2 is live. You can get it [here](https://www.spigotmc.org/resources/governor.101482/). This should fix your issue, but if you are still having problems let me know.
